# -*- coding: utf-8 -*-
"""ML-MINOR-MAY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xUqUxqYnJK5A2jbMp0DjiGGlVeLUePee

#Creating a Ml model to find whether a patient has diabetes or not using Logistic Regrssion with the given data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Reading the data from the given csv file using pandas


"""

df = pd.read_csv('diabetes.csv')
df

"""Finding the correlation matrix"""

df.corr()

"""Defining input and output from the given data"""

x = df[['Pregnancies','Glucose','Insulin','BMI','DiabetesPedigreeFunction','Age']].values
x

y = df['Outcome'].values
y

"""Spliting the given input and output dataset into train data and test data"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

"""Standarization of the given data"""

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()

"""Training the model using the training data """

classifier.fit(x_train,y_train)

"""Testing the model using the test data as input"""

y_pred = classifier.predict(x_test)
y_pred

"""Finding the accuracy and confusion matrix of the model"""

from sklearn.metrics import accuracy_score , confusion_matrix

accuracy_score(y_test , y_pred)

confusion_matrix(y_true=y_test,y_pred=y_pred)
